### ISSUE TITLE
Python 3.5

### ISSUE THREAD

**Issue by quarter42** [msracver/Deep-Exemplar-based-Colorization#10]
Is it possible to compile for Python 3.5?  I'm getting errors that relate to python27.lib but I have Caffe compiled for Python 3.5.

**Comment by hmmlillian** [comment]
@quarter42 Hello, which part do you mean compiled for Python 3.5?
The **Similarity Sub-net** is implemented with Caffe in C++ in which pycaffe does not need compiling, which the **Colorization Sub-net** using Pytorch should be completely compatible in Python 3.5.
