### ISSUE TITLE
 Colorization Sub-net use which python and lib version

### ISSUE THREAD

**Issue by Zebrocode** [msracver/Deep-Exemplar-based-Colorization#12]
Could you please tell me the pytorch version and the torchvision version and python version you used to run the Colorization Sub-net?

**Comment by hmmlillian** [comment]
@Zebrocode I just tested with the following environment:
python 3.6.7
pytorch 1.0.0 (py3.6_cuda90_cudnn7_1)
torchvison 0.2.2
It works.

**Comment by Zebrocode** [comment]
Thanks for the help. And because i want to run the similarity_subnet and colorization_subnet together.And caffe needs  CUDA 8.0.  So i tryed following environment and run them together.
my OS is win10.
python 3.7.2
pytorch 1.0.1(CUDA 8.0 cudnn 5.1)
torchvision 0.1.8
i think it may facilitate others who want to run your whole project in the same OS.  ^-^

**Comment by Zebrocode** [comment]
sorry about bother you again,i meet a problem when i want to run deep_image_analogy.exe to reproduce a new bidirecton mapping function. logs as follow:

![`%Z1N8_WJ{$%E79M1@W%{9R](https://user-images.githubusercontent.com/28325377/60491704-f3965f80-9cdb-11e9-9a18-2771247a8199.png)

**Comment by hmmlillian** [comment]
@Zebrocode 
For the error, please refer to [msracver/Deep-Image-Analogy#11](https://github.com/msracver/Deep-Image-Analogy/issues/11), and your problem may be solved by disabling TDR.

**Comment by Zebrocode** [comment]
I find disable TDR can't help. And the exe is complied by myself from the project i download from your repository. I can just solve it by noting the check called CUDA_POST_KERNEL_CHECK in pooling_layer.cu.
But if i use your demo exe directly,the project can run well with the TDR disabled.

**Comment by hmmlillian** [comment]
@Zebrocode Did you enable or disable CUDA_POST_KERNEL_CHECK? What kind of Cuda error did you meet?

**Comment by Zebrocode** [comment]
I didn't do anything to enable or disable CUDA_POST_KERNEL_CHECK and don't know how to enable or disable it. 
The error is just the same as above let me show you again.
![图片](https://user-images.githubusercontent.com/28325377/60692917-bf54b600-9f0a-11e9-8de3-7e0ee6119b0b.png)
so i have no other better idea. i can just note the code in pooling_layer.cu:
![图片](https://user-images.githubusercontent.com/28325377/60693044-4b66dd80-9f0b-11e9-9153-572a6d1213e0.png)
![图片](https://user-images.githubusercontent.com/28325377/60693069-5faada80-9f0b-11e9-909b-f3b8d0b1d8b0.png)
After I note the two places and recomplie caffe and deep_image_analogy again, the error disappeared.
