### ISSUE TITLE
what is the construction of combo file? 

### ISSUE THREAD

**Issue by youyingyin** [msracver/Deep-Exemplar-based-Colorization#15]
Hi, I have read the combo file in python with 'rb', but I can not figure out the meaning of it.

**Comment by hmmlillian** [comment]
@youyingyin You can refer to the code in ``Deep-Exemplar-based-Colorization/similarity_subnet/windows/similarity_combo/source/Combo.cu`` (L265~L388), which includes all details of the content in _combo_ file.

**Comment by youyingyin** [comment]
> 265~L388

Thanks, I read the example combo file, but it seems the output is not matched  with the Combo.cu file.
![未标题-1](https://user-images.githubusercontent.com/33154862/63118809-3634a280-bfd1-11e9-8351-85533bccfe14.jpg)

**Comment by hmmlillian** [comment]
@youyingyin Please refer to our Python code of combo loader:
 ``Deep-Exemplar-based-Colorization/colorization_subnet/lib/TestDataset.py`` (L34~L84).

**Comment by youyingyin** [comment]
> @youyingyin Please refer to our Python code of combo loader:
> `Deep-Exemplar-based-Colorization/colorization_subnet/lib/TestDataset.py` (L34~L84).

Thank you so much !
