### ISSUE TITLE
Color Transfer

### ISSUE THREAD

**Issue by AliAsafPolat** [msracver/Deep-Exemplar-based-Colorization#18]
Hello, I did not get where is the exact point that color transfer happens in your code. I mean /colorization_subnet/test.py . Could you please explain to me?

Best regards.

**Comment by hmmlillian** [comment]
@AliAsafPolat In Line86 in test.py, we pass the concatenated input to the colorization network and get the predicted chrominance channels, which will combine with the original luminance channel to achieve the final colorization result.

**Comment by AliAsafPolat** [comment]
Thank you so much.
