### ISSUE TITLE
Deep Image Analogy for Colorization

### ISSUE THREAD

**Issue by AliAsafPolat** [msracver/Deep-Exemplar-based-Colorization#19]
Hello, i could not understand how did you use Deep Image Analogy for colorization. I examined your colorization_subnet/test.py code and did not find anything for Image Anology. Could you please explain the correlation between colorization and Deep Image Analogy ?

Thanks,
Best Regards.

**Comment by hmmlillian** [comment]
@AliAsafPolat Deep Image Analogy is used to build correspondence between the color reference image and the target grayscale image at pre-processing; then based on the correspondence, the colorization network will propagate and predict correct chrominance channels. For more details, please refer to our paper.

**Comment by AliAsafPolat** [comment]
I understand but did not see the part of code about this. You said that "based on the correspondence, the colorization network will propagate and predict" but how the colorization network use these input. Is it read from file or somewhere? 

As I understand output of Deep Image Analogy  saved to flow files and output of Similarity Subnet saved to combo files. Am i right? 

I saw that you read combofile in the TestDataset.py but did not find where did you read flow files.

**Comment by hmmlillian** [comment]
@AliAsafPolat Yes, as you understand, the output of Deep Image Analogy is saved to flow files and then we read the flow files to compute similarity (code shown in Deep-Exemplar-based-Colorization/similarity_subnet/windows/similarity_combo/source/main.cpp) and save to combo files.

**Comment by AliAsafPolat** [comment]
Thank you very much! I got it now.
