### ISSUE TITLE
Could you please add the baidu cloud drive link?

### ISSUE THREAD

**Issue by peif1987** [msracver/Deep-Exemplar-based-Colorization#2]
I am sorry that I can not download the model from Dropbox, the speed is very slow, even I use the VPN,  
So could you please give the download link of the Baidu cloud drive ? 
Thank you very much!

**Comment by hmmlillian** [comment]
Sure, we have uploaded the three model files to Baidu Cloud Drive:
1. vgg_19_gray_bn: Link: https://pan.baidu.com/s/1N9B1C6FWnDFib9hRk4-TDA Pwd: c9ss
2. vgg_19: Link: https://pan.baidu.com/s/1p5Ikwy-ZWD37cXGgOehfzQ Pwd: y766
3. colorization_subnet: Link: https://pan.baidu.com/s/1LHyvBfEryCtAkfUlLX_V6Q Pwd: nwkp
