### ISSUE TITLE
Any plan to publish your filtered Hollywood2 dataset?

### ISSUE THREAD

**Issue by k-zha14** [msracver/Deep-Exemplar-based-Colorization#22]
Hi, guys! It's a really fascinating job. Right now, I also work on a similar problem. I just wonder if you have any plan to publish this modified dataset? Thanks a lot!

**Comment by hmmlillian** [comment]
@k-zha14 I think you mean the Hollywood2 dataset used in Deep Examplar-based Video Colorization that is NOT in this repository. But you may download that dataset from https://www.di.ens.fr/~laptev/actions/.
