### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by AliAsafPolat** [msracver/Deep-Exemplar-based-Colorization#24]
When i try to run your model sometimes it successfully runs but then when i try with other image i get this ("Check failed: error == cudaSuccess (2 vs. 0)  out of memory") error. Do you have any idea about this? Is it possible that depends on image size?  

I have 4 GB GPU
GeForce GTX 950M  
Windows10

**Comment by hmmlillian** [comment]
@AliAsafPolat I think you can disable TDR to solve this problem. To disable TDR, you may change the TDR-related registry keys like this https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys, or use NVIDIA Nsight Development Platform (https://docs.nvidia.com/gameworks/content/developertools/desktop/timeout_detection_recovery.htm) if you use NVIDIA GPU on Windows.

**Comment by AliAsafPolat** [comment]
Yes i have seen this solution from previous issues and changed my settings already. But still i get same error. As i said before, sometimes i can run successfully.

**Comment by hmmlillian** [comment]
@AliAsafPolat That may be caused by your limited GPU memory and sometimes it does run out of memory. If you reduce the image resolution, that should be helpful.

**Comment by AliAsafPolat** [comment]
So do i think. Thanks for help. Best regards
