### ISSUE TITLE
The meaning of theta parameter in the paper

### ISSUE THREAD

**Issue by TSeMDiD** [msracver/Deep-Exemplar-based-Colorization#25]
Hi! It's an impressive work. 
I am trying to understand the implemented method. In particular, how is the theta parameter used in the Colorization Sub-Network. Formula 3 or Figure 4 in the paper do not give a detailed description.

**Comment by hmmlillian** [comment]
@TSeMDiD It seems we explain in the text as "Both branches share the same network C and weight θ but are associated with their own input and loss function", θ is network weight.
