### ISSUE TITLE
what is combo file? How to get it

### ISSUE THREAD

**Issue by Rokuki** [msracver/Deep-Exemplar-based-Colorization#4]
I run the pytorch part and get this error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/combo_new/1_1r.combo'
```
I would appreciate if you could help me on this matter,thx

**Comment by cmlatsim** [comment]
Have you executed in the following way?

(1) Please create bidirectional flow files and put them under the folder "flow/" (ad default we use "Deep Image Analogy"(source code in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/similarity_subnet/windows/deep_image_analogy] and exe in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/demo/exe]));

(2) Please generate similarity maps by using similarity_combo.exe and then the corresponding combo files will be generated in the folder "combo_new/" (source code in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/similarity_subnet/windows/similarity_combo] and exe in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/demo/exe]);

(3) Finally, please do colorization with our pretrained model by executing Python test.py.

This error means you did not use (1) and (2) to generate valid combo files to be used by Colorization Subnet. Please try the above steps. Thanks!

**Comment by hmmlillian** [comment]
Have you executed in the following way?

(1) Please create bidirectional flow files and put them under the folder "flow/" (ad default we use "Deep Image Analogy"(source code in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/similarity_subnet/windows/deep_image_analogy] and exe in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/demo/exe]));

(2) Please generate similarity maps by using similarity_combo.exe and then the corresponding combo files will be generated in the folder "combo_new/" (source code in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/similarity_subnet/windows/similarity_combo] and exe in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/demo/exe]);

(3) Finally, please do colorization with our pretrained model by executing Python test.py.

This error means you did not use (1) and (2) to generate valid combo files to be used by Colorization Subnet. Please try the above steps. Thanks!

**Comment by Rokuki** [comment]
Thank you for your reply , so it can't run on ubuntu,right?

**Comment by Rokuki** [comment]
> Have you executed in the following way?
> 
> (1) Please create bidirectional flow files and put them under the folder "flow/" (ad default we use "Deep Image Analogy"(source code in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/similarity_subnet/windows/deep_image_analogy] and exe in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/demo/exe]));
> 
> (2) Please generate similarity maps by using similarity_combo.exe and then the corresponding combo files will be generated in the folder "combo_new/" (source code in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/similarity_subnet/windows/similarity_combo] and exe in [https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/demo/exe]);
> 
> (3) Finally, please do colorization with our pretrained model by executing Python test.py.
> 
> This error means you did not use (1) and (2) to generate valid combo files to be used by Colorization Subnet. Please try the above steps. Thanks!

Thank you for your reply , so it can't run on ubuntu,right?

**Comment by hmmlillian** [comment]
No, we're sorry we haven't converted the Similarity SubNet to Linux code yet.

**Comment by Rokuki** [comment]
> No, we're sorry we haven't converted the Similarity SubNet to Linux code yet.

I see,it's a awesome project.Thank you
