### ISSUE TITLE
How can I generate the flow files？

### ISSUE THREAD

**Issue by TingMAC** [msracver/Deep-Exemplar-based-Colorization#6]
How can I generate the flow files using Deep-Image-Analogy when I want to colorize my own pictures?

**Comment by hmmlillian** [comment]
If you use Deep Image Analogy, please download deep_image_analogy.vcxproj under our folder "similarity_subnet\windows\deep_image_analogy\" and
(1) Edit "CommonSettings.props.example" (under "similarity_subnet\windows\") to make the cuda version and cudnn path (if used) in it match yours, and save it as "CommonSettings.props" .
(2) Open solution Caffe (under "similarity_subnet\windows\") and add deep_image_analogy (under "similarity_subnet\windows\deep_image_analogy\") project.
(3) Build Caffe and the project deep_image_analogy.

**Comment by TingMAC** [comment]
Thank you. But the same error as cccusername's comes up
Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0) CUDNN_STATUS_EXECUTION_FAILED.
Another question:
I run the command exe\deep_image_analogy.exe models\deep_image_analogy\ example\ 0 2 0 with my laptop and it costs about 100 seconds before the error comes up, which is much lower than the time consumption you mentioned in your paper. I know you use better GPUs, is the time used on my computer reasonable?

**Comment by hmmlillian** [comment]
@TingMAC 
(1) For the error, please refer to the solution () https://github.com/msracver/Deep-Image-Analogy/issues/11

**Comment by hmmlillian** [comment]
@TingMAC 
For the error, please refer to https://github.com/msracver/Deep-Image-Analogy/issues/11 , and your problem may be solved by disabling TDR.
For the speed, if the image is resized to the short edge no larger than 256 pixels, it should be slowed down by the GPU.
