### ISSUE TITLE
Color Reference Recommendation

### ISSUE THREAD

**Issue by lisa92203** [msracver/Deep-Exemplar-based-Colorization#7]
Does it contain the "Color Reference Recommendation" part in this work?

**Comment by hmmlillian** [comment]
@lisa92203 Sorry, we did not involve the "Color Reference Recommendation" in this repository because it relies on the compressed deep features of ImageNet for searching which is too large to upload.

**Comment by lisa92203** [comment]
Got it! Thank you for the reply.

**Comment by hmmlillian** [comment]
@lisa92203 We released the feature database and source code on GitHub (https://github.com/hmmlillian/Gray-Image-Retrieval). Hope it helps.

**Comment by lisa92203** [comment]
Thank you very much!
