### ISSUE TITLE
Is there the Linux version of the code?

### ISSUE THREAD

**Issue by TruePhone** [msracver/Deep-Exemplar-based-Colorization#8]
The project is very awesome and it would be more convenient for testing if there would be the Linux version of the code. I know the Colorization Subnet is based on Pytorch, which is easily used on Linux, so I hope I can get the Linux version of the Similarity SubNet if possible. Thank you very much.

**Comment by hmmlillian** [comment]
@TruePhone The **Similarity SubNet** (and **Deep Image Analogy** if you use it to build correspondence) is implemented in C++. It should be easy to transplant to Linux.  **Deep Image Analogy** already has a Linux version (https://github.com/msracver/Deep-Image-Analogy/tree/linux) and our **Similarity SubNet** is actually built based on it. You may copy the source code from [_Deep-Exemplar-based-Colorization/similarity_subnet/windows/similarity_combo/_](https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/similarity_subnet/windows/similarity_combo) to [_msracver/Deep-Image-Analogy/tree/linux_](https://github.com/msracver/Deep-Image-Analogy/tree/linux) and slightly modify it on Linux.

**Comment by TruePhone** [comment]
@hmmlillian Thanks for your prompts very much. I will have a try.

**Comment by gaojxx** [comment]
@TruePhone Hello, I am also planning to tranfer it to Linux version recently. Now I can compile the Deep-Image-Analogy successfully, but can't compile similarity_combo. So, could you provide the executable file of similarity_combo if you compile it successfully? Thanks very much!

**Comment by xuzhongyou** [comment]
> @TruePhone The **Similarity SubNet** (and **Deep Image Analogy** if you use it to build correspondence) is implemented in C++. It should be easy to transplant to Linux. **Deep Image Analogy** already has a Linux version (https://github.com/msracver/Deep-Image-Analogy/tree/linux) and our **Similarity SubNet** is actually built based on it. You may copy the source code from [_Deep-Exemplar-based-Colorization/similarity_subnet/windows/similarity_combo/_](https://github.com/msracver/Deep-Exemplar-based-Colorization/tree/master/similarity_subnet/windows/similarity_combo) to [_msracver/Deep-Image-Analogy/tree/linux_](https://github.com/msracver/Deep-Image-Analogy/tree/linux) and slightly modify it on Linux.

Thank you for your job, but i think most of people work on linux. Please give a intergrated version about linux or tell us what we should do  in detail.

**Comment by jqueguiner** [comment]
https://github.com/msracver/Deep-Exemplar-based-Colorization/pull/13

**Comment by mattclifford1** [comment]
Did anyone manage to get this transfer successfully to Linux?

**Comment by ncianeo** [comment]
#21 
I got this transfer successfully to linux!

**Comment by Travsmakoy** [comment]
@ncianeo How ? Can you share it with me?

**Comment by ncianeo** [comment]
@Travsmakoy Use this repository: https://github.com/ncianeo/Deep-Exemplar-based-Colorization/tree/linux-docker-cv-caffe-build
